// src/Presentation/WebApp/Angular/Client/src/features/sign-out/ui/sign-out-dropdown/sign-out-dropdown.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Store } from '@ngrx/store';
import { sessionModel } from '~entities/session';
import { routePath } from '~shared/router';

@Component({
  selector: 'sign-out-dropdown',
  templateUrl: './sign-out-dropdown.component.html',
  styleUrl: './sign-out-dropdown.component.scss'
})
export class SignOutDropdownComponent {

  constructor(private readonly store: Store, private router: Router) { }

  onClickLogout() {
    this.store.dispatch(sessionModel.actions.logout());
    this.router.navigate([routePath.home()]);
  }
}

// src/Presentation/WebApp/React/Client/src/features/authentication/sign-out/ui/sign-out-dropdown/sign-out-dropdown.tsx
import { useNavigate } from 'react-router-dom';
import { sessionModel } from '~entities/session';
import { useAppDispatch } from '~shared/lib/store';
import { routePath } from '~shared/router';

export const SignOutDropdown = () => {
    const dispatch = useAppDispatch();
    const navigate = useNavigate();

    function onClickLogout() {
        dispatch(sessionModel.thunks.logout());
        navigate(routePath.home());
    }

    return (
        <a className="dropdown-item" onClick={onClickLogout}>Sign out</a>
    );
}
